Adding repoformat

diff --git a/wah-repo-add b/wah-repo-add
--- a/wah-repo-add
+++ b/wah-repo-add
@@ -11,6 +11,7 @@ cmdChk() {
 }
 
 NAME="Make Wah-Package wah repo add"
+repoformat=1
 cmdChk dirname
 
 if [ -f "${WAHROOT}/usr/lib/makewpkg/core.wah" ]; then
@@ -32,7 +33,7 @@ source "${CORE}/core.wah"
 
 wah-repo(){
 	if [ -f "$1.db" ]; then
-		case "$(file $1.db|cut -d ' ' -f2)" in
+		case "$(file $1.db | cut -d ' ' -f2)" in
 			"ASCII")
 				INFO "$1.db is plain text, moving to $1"
 				cmdChk mv
@@ -54,39 +55,41 @@ wah-repo(){
 				zstd wah.db -o wah -d
 			;;
 			*)
-				ERROR "$(file $1 | cut -d ' ' -f2) not supported" 3
+				ERROR "$(file $1.db | cut -d ' ' -f2) not supported" 3
 			;;
 		esac
+		if ! [ "$(head -n1 $1)" == "REPOFORMAT:$repoformat" ]; then
+			ERROR "Unsuported or invalid format" 4
+		fi
 	else
 		INFO "$1.db don't exist, creatting $1"
-		cmdChk touch
-		touch $1
+		echo -e "REPOFORMAT:$repoformat\n" > $1
 	fi
 
 	unset localname localver localvercode url arch localdesc localdepends localoptdepends localconflicts localprovides localgroups
 	eval $(tar -xzO -f $2 ./.PKGINFO)
 
-	echo "PKG:'$localname'" >> "$1"
-	echo "VER:'$localver'" >> "$1"
+	echo "PKG:$localname" >> "$1"
+	echo "VER:$localver" >> "$1"
 	echo "VERCODE:$localvercode" >> "$1"
 
 	if ! [ -z "$url" ]; then
-		echo "URL:'$url'" >> "$1"
+		echo "URL:$url" >> "$1"
 	fi
 
-	echo "ARCH:'$arch'" >> "$1"
+	echo "ARCH:$arch" >> "$1"
 
 	if ! [ -z "$localdesc" ]; then
-		echo "DESC:'$localdesc'" >> "$1"
+		echo "DESC:$localdesc" >> "$1"
 	fi
 
 	if ! [ -z "$localdepends" ]; then
 		printf "DEPS:" >> "$1"
 		for dep in "${localdepends[@]}"; do
 			if [ "${localdepends[0]}" = "$dep" ]; then
-				printf "'$dep'" >> "$1"
+				printf "$dep" >> "$1"
 			else
-				printf ",'$dep'" >> "$1"
+				printf ",$dep" >> "$1"
 			fi
 		done
 		echo >> "$1"
@@ -96,9 +99,9 @@ wah-repo(){
 		printf "OPTDEPS:" >> "$1"
 		for dep in "${localoptdepends[@]}"; do
 			if [ "${localoptdepends[0]}" = "$dep" ]; then
-				printf "'$dep'" >> "$1"
+				printf "$dep" >> "$1"
 			else
-				printf ",'$dep'" >> "$1"
+				printf ",$dep" >> "$1"
 			fi
 		done
 		echo >> "$1"
@@ -108,9 +111,9 @@ wah-repo(){
 		printf "CONFLICS:" >> "$1"
 		for con in "${localconflicts[@]}"; do
 			if [ "${localconflicts[0]}" = "$con" ]; then
-				printf "'$con'" >> "$1"
+				printf "$con" >> "$1"
 			else
-				printf ",'$con'" >> "$1"
+				printf ",$con" >> "$1"
 			fi
 		done
 		echo >> "$1"
@@ -120,9 +123,9 @@ wah-repo(){
 		printf "PROV:" >> "$1"
 		for prov in "${localprovides[@]}"; do
 			if [ "${localprovides[0]}" = "$prov" ]; then
-				printf "'$prov'" >> "$1"
+				printf "$prov" >> "$1"
 			else
-				printf ",'$prov'" >> "$1"
+				printf ",$prov" >> "$1"
 			fi
 		done
 		echo >> "$1"
@@ -132,9 +135,9 @@ wah-repo(){
 		printf "GROUPS:" >> "$1"
 		for group in "${localgroups[@]}"; do
 			if [ "${localgroups[0]}" = "$group" ]; then
-				printf "'$group'" >> "$1"
+				printf "$group" >> "$1"
 			else
-				printf ",'$group'" >> "$1"
+				printf ",$group" >> "$1"
 			fi
 		done
 		echo >> "$1"
